apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-api-deployment
  labels:
    app: test-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - name: test-api
          image: noahgels/test-api:count
          ports:
            - containerPort: 50000
